# Site settings
name: 少即是多
email: high0048@126.com
author: Kenny Kong
url: http://kennykong.github.io
resume_site: http://kennykong.github.io
github: https://github.com/kennykong/
#baseurl: "/LessOrMore"
description: Actually, less is more!
meta_description: 孔祥毅; 个人博客; 心能诚意,事上磨练; 知行合一
motto: 知行合一，事上磨练
banner: 无善无恶心之体，有善有恶意之动，知善知恶是良知，为善去恶是格物。

#permalink: /:categories/:year/:month/:day/:title/
permalink: /:year/:month/:day/:title/
paginate: 10

exclude: ['README.md', 'Gemfile.lock', 'Gemfile', 'Rakefile']

github_username: high0048
highlighter: Pygments

# Build settings
markdown: kramdown

baidu_analysis: eca4fe043b0142ff6fe81b0373c54134

FB:
  comments :
    provider : changyan
    duoshuo:
        short_name : high0048
    disqus :
        short_name : high0048
    changyan :
        appid : cyt0FC2lp
        conf : prod_df8753ed1936f0e8dfb46e41f3b26694
    # facebook :
    #   appid : 123
    #   num_posts: 5
    #   width: 580
    #   colorscheme: light
